version: "3"

services:
    php:
        container_name: laravel_backup_php
        build: ./.docker/php
        tty: true
        volumes:
            - ./:/laravel-package
        working_dir: /laravel-package
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=laravel_db
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=password
        links:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: laravel_backup_mysql
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 33066:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=laravel_db
            - MYSQL_USER=laravel_user
            - MYSQL_PASSWORD=password
        restart: on-failure

volumes:
    db_data:
